version: "3.8"

services:
  wiki:
    build: .
    image: wiki
    container_name: wiki
    ports:
      - 80:80
    volumes:
      - wiki:/wiki
    depends_on:
      - mysql
      - redis
    networks:
      - default

  redis:
    image: redis:6.0.10
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /usr/app/redis/redis.conf:/etc/redis/redis.conf
      - /usr/app/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - default
  
  mysql:
    image: mysql:5.7.26
    container_name: mysql
    ports:
    - 3306:3306
    volumes:
      - /usr/app/mysql/data:/var/lib/mysql
      - /usr/app/mysql/conf:/etc/mysql
      - /usr/app/mysql/wiki.sql:/docker-entrypoint-initdb.d/wiki.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      TZ: Asia/Shanghai
    networks:
      - default

volumes:
  wiki:

networks:
  default: