server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://192.168.110.225:3306/wiki?characterEncoding=UTF8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liuziye
    password: 1994

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  