server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.0.104
    password:
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间
        max-idel: 5 #连接池最大空闲连接
        min-idel: 5 #连接池最小空闲连接
    timeout: 10000

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  
logging:
  level: 
    com.dorohedoro.wiki.mapper: info

